name: Telegram Bot

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install telebot
          pip install flask
          pip install aiogram

      - name: Make scripts executable
        run: chmod +x *

      - name: Run bot
        run: python m.py  # Replace with your bot script name
